### ISSUE TITLE
Find bar doesn't search for certain words on some pages

### ISSUE THREAD

**Issue by iG8R** [hoothin/SearchJumper#103] opened 2023-11-03 04:27 UTC
**Describe the bug**
Find bar doesn't search for certain words on https://github.com/WerWolv/ImHex/releases/tag/v1.31.0

**To Reproduce**
1. Go to https://github.com/WerWolv/ImHex/releases/tag/v1.31.0
2. Bring up the Find bar and enter the word `gpu`
3. Although this word is present on the page nothing will be found.

**Expected behavior**
All words that are present on any page will be found.

**Screenshots**
![image](https://github.com/hoothin/SearchJumper/assets/11407417/c282ba42-81a5-4023-af44-f00da2e35a47)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19045.2673] 64bit
 - Browser: Firefox 119.0 64bit

**Comment by hoothin** [comment] 2023-11-03 04:29
Use regExp like `/gpu/` `/GPU/`

**Comment by hoothin** [comment] 2023-11-03 04:33
You can get only exact word if you input 'GPU', without 'NoGPU' 'YesGPU'

**Comment by iG8R** [comment] 2023-11-03 04:48
Is it possible to add an option for the search panel to work the same way as the standard search panel in the browser, that is, not distinguishing between exact and compound words?

**Comment by hoothin** [comment] 2023-11-03 07:37
I've updated to change content from `str` to `/str/i` automatically if your input text has no space.

**Comment by hoothin** [comment] 2023-11-03 07:41
You can double click the word frame in search input to change its behaviour.

**Comment by iG8R** [comment] 2023-11-03 07:56
Thanks a lot.

**Comment by iG8R** [comment] 2023-11-06 01:06
Another issue.

![image](https://github.com/hoothin/SearchJumper/assets/11407417/f4798200-fbb9-4b84-966b-7b5c0c336846)

**Comment by hoothin** [comment] 2023-11-06 02:35
Thanks for report. It's a know issue, cause that's not a actual text node, but a css text.
![image](https://github.com/hoothin/SearchJumper/assets/5361213/088b5db3-1699-407f-b26f-9fca43d7e7bc)
I could load the text from github and highlight with a special code, but that's too ugly.
I will fix it after I have a good idea.

**Comment by iG8R** [comment] 2023-11-06 03:36
Thanks a lot.

**Comment by iG8R** [comment] 2023-11-06 12:16
I apologize, in my previous post I didn't provide a link to the page where I took the screenshot.
https://github.com/Ixiko/AHK-libs-and-classes-collection/blob/master/classes/class_LoadPictureType.ahk

![image](https://github.com/hoothin/SearchJumper/assets/11407417/2104599a-94a0-4410-b03c-bca70884ea8c)

**Comment by hoothin** [comment] 2023-11-06 12:53
Sorry I didn't count the scroll bar. You can try again.
![image](https://github.com/hoothin/SearchJumper/assets/5361213/4f0c884c-8ba9-4d98-bd10-c1576b8f47b9)

**Comment by iG8R** [comment] 2023-11-06 13:15
[SearchJumper-FindBar-github-Video_2023-11-06_150939.webm](https://github.com/hoothin/SearchJumper/assets/11407417/0cb27fbe-172d-4fc0-b931-f37611323ee9)

**Comment by hoothin** [comment] 2023-11-07 00:23
Thanks for test & report, I didn't test switching with enter. It's fixed now.

**Comment by iG8R** [comment] 2023-11-07 04:58
Thanks for work.

[SearchJumper-FindBar-github-2-Video_2023-11-07_064924.webm](https://github.com/hoothin/SearchJumper/assets/11407417/d148b24c-7b82-48e8-90dd-0cc7c32d97dc)

**Comment by iG8R** [comment] 2023-11-07 05:07
In addition to the fact that the number of found words on the page changes, also note that every now and then SearchJumper misses, not exactly hitting the word with a crosshair, and sometimes, as it were, thinks halfway to the word.

**Comment by hoothin** [comment] 2023-11-07 05:15
It's ordinary behaviour and as same as build-in find in page of firefox. Github is build with React and the dom will refresh when you scroll even though the page seems to be unchanged.

**Comment by iG8R** [comment] 2023-11-07 05:17
OK, I got it.

**Comment by iG8R** [comment] 2023-11-07 07:21
Is there a way to search by entire phrase rather than by words?

[SearchJumper-FindBar-github-3-Video_2023-11-07_091518.webm](https://github.com/hoothin/SearchJumper/assets/11407417/561f4f77-c1fc-4d7c-93cf-167b81a5a88d)

**Comment by hoothin** [comment] 2023-11-07 07:35
$o or $c. You can see detail when you hover mouse on the input bar

**Comment by iG8R** [comment] 2023-11-07 07:44
Is it possible make it switchable, like the "Pin search text" and "Sidebar to locate" icons on the right?

**Comment by hoothin** [comment] 2023-11-07 07:53
Sorry, but I don't like the switchable function of sth like "case sensitive", "whole phrase".
What about ignore delimiter when input phrase contains space?

**Comment by iG8R** [comment] 2023-11-07 08:11
It’s just that with such a switch it would be convenient to switch between searching for the entire phrase and words individually. For example, the user initially enter github copilot and find the entire phrase; if they need to find individual words, click on the icon and a search for individual words occurs. If the entire phrase will be searched only if the delimiters contain spaces, then in order to search by words, you will need to manually remove the delimiters.
At the same time, separators can be used to indicate that when switching to word search mode, words will be searched individually or jointly.
For example, the phrase `about+ignore delimiter+when input` will initially be searched in its entirety, switching to a word search will search `about+ignore` `delimiter+when` `input`. If `about +ignore delimiter +when input` was entered, i.e. there will be a space before `+`, then switching to a word search will search for `about` `ignore when` `delimiter ` `input`.

**Comment by iG8R** [comment] 2023-11-07 10:52
Another page with a Find bar bug.
https://habr.com/ru/articles/548064/
search query: `general.smoothScroll.durationToIntervalRatio`

![image](https://github.com/hoothin/SearchJumper/assets/11407417/9dde4cfe-c6a8-4ff7-b9de-210f0505dc23)
![image](https://github.com/hoothin/SearchJumper/assets/11407417/8822a4f2-d5cf-4120-93a8-3ae92e5326cd)

**Comment by hoothin** [comment] 2023-11-07 10:59
It's not a bug, the words are in different elements. To join all the text node for finding cross element will cost much CPU time. So I ignore this situation.

**Comment by iG8R** [comment] 2023-11-07 11:05
Then there is a situation where the user cannot be 100% sure when using the Findbar that all occurrences of what they are looking for have been found.

**Comment by iG8R** [comment] 2023-11-07 11:08
For example, as it happened to me - I clicked on a link from Google and saw that SearchJumper did not highlight any words, then I manually called the Findbar and still without success. After that, I decided to just check with the standard Firefox search just in case, and it turned out that the necessary keywords were indeed on the page.

**Comment by iG8R** [comment] 2023-11-07 11:27
Is it possible to make an option to make the functions
`Highlight keywords on the search engine results page`
`Highlight keywords on the page opened by click on the search engine`
work in the following way - when finishing a search in the search engine or opening the page from the search engine, so that the search words are not immediately highlighted, but only when the Findbar is brought up, then the words from the search query are already present in it and highlighted on the page?

**Comment by hoothin** [comment] 2023-11-14 01:35
It's now supported.

**Closed by hoothin** 2023-11-14 01:35 UTC
